import = ['~/.config/alacritty/catppuccin-mocha.toml']

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 8 }
decorations = "buttonless"
opacity = 0.8
blur = true
startup_mode = "Windowed"
option_as_alt = "Both"

[scrolling]
history = 50000

[font]
size = 15

[font.normal]
family = "UDEVGothic35LG Nerd Font"
style = "Regular"

[keyboard]
bindings = []
