#!/bin/bash

set -e

cd ~

# Install Homebrew
if [ ! -f /opt/homebrew/bin/brew ]; then
	echo "Installing Homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
else
  echo "Homebrew already installed."
fi

# Clone my dotfiles
if [ ! -d ~/dotfiles ]; then
  echo "Have you registered your public key on GitHub?"
	select yn in "Yes"; do
		case $yn in
		  Yes ) break;;
		esac
	done
	echo "Cloning dotfiles..."
	git clone git@github.com:tosaka07/dotfiles.git
else
	echo "dotfiles already cloned."
fi

# Create config directory
if [ ! -d ~/.config ]; then
	echo "Creating ~/.config directory..."
	mkdir ~/.config
fi

# Install z4h
echo "Install z4h..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"

rm ~/.zshenv
rm ~/.zshrc
rm ~/.p10k.zsh

# Symlink
echo "Symlink files..."
ln -s ~/dotfiles/.zshenv ~/
ln -s ~/dotfiles/.zshrc ~/
ln -s ~/dotfiles/.gitconfig ~/
ln -s ~/dotfiles/.asdfrc ~/
ln -s ~/dotfiles/.tmux.conf ~/
ln -s ~/dotfiles/.emacs.d ~/
ln -s ~/dotfiles/.p10k.zsh ~/
ln -s ~/dotfiles/.asdfrc ~/
ln -s ~/dotfiles/.tool-versions ~/
ln -s ~/dotfiles/.config/nvim ~/.config/ 

# asdf
echo "Install SDK via asdf"
asdf plugin add flutter
asdf plugin add nodejs
asdf plugin add deno
asdf plugin add python
asdf plugin add ruby
asdf plugin add dart https://github.com/tosaka07/asdf-dart
asdf plugin update dart abaed79c72b1c406f1c1a1a307540aa9c0d7b6c4

asdf install

# nvim settings
echo "Configure pip for nvim..."
python3 -m pip install --user --upgrade pynvim 
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
python2 get-pip.py && rm get-pip.py
python2 -m pip install --user --upgrade pynvim


# Screenshot settings
echo "Configure Screenshot settings..."
defaults write com.apple.screencapture type jpg 
defaults write com.apple.screencapture name Screenshot 
defaults write com.apple.screencapture location ~/Pictures/Screenshot/

echo "Done!"
