#!/bin/bash

# Symlink
ln -s ~/dotfiles/.zshenv ~/
ln -s ~/dotfiles/.zshrc ~/
ln -s ~/dotfiles/.gitconfig ~/
ln -s ~/dotfiles/.asdfrc ~/
ln -s ~/dotfiles/.tmux.conf ~/
ln -s ~/dotfiles/.p10k.zsh ~/
ln -s ~/dotfiles/.asdfrc ~/
ln -s ~/dotfiles/.tool-versions ~/
ln -s ~/dotfiles/.config/nvim ~/.config/ 

# asdf
asdf plugin add flutter
asdf plugin add nodejs
asdf plugin add deno
asdf plugin add python
asdf plugin add ruby
asdf plugin add dart https://github.com/tosaka07/asdf-dart
asdf plugin update dart abaed79c72b1c406f1c1a1a307540aa9c0d7b6c4

pushd ~/
asdf install
popd

# nvim settings
python3 -m pip install --user --upgrade pynvim 
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py
python2 get-pip.py && rm get-pip.py
python2 -m pip install --user --upgrade pynvim
